//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "direct_chat_reaction")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub owner_id: Uuid,
  #[sea_orm(primary_key, auto_increment = false)]
  pub reacted_direct_chat_sender_id: Uuid,
  #[sea_orm(primary_key, auto_increment = false)]
  pub reacted_direct_chat_receiver_id: Uuid,
  #[sea_orm(primary_key, auto_increment = false)]
  pub reacted_direct_chat_created_at: DateTimeWithTimeZone,
  pub created_at: DateTimeWithTimeZone,
  pub reaction_emoji: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::direct_chat::Entity",
    from = "(Column::ReactedDirectChatSenderId, Column::ReactedDirectChatReceiverId, Column::ReactedDirectChatCreatedAt)",
    to = "(super::direct_chat::Column::SenderId, super::direct_chat::Column::ReceiverId, super::direct_chat::Column::CreatedAt)",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  DirectChat,
  #[sea_orm(
    belongs_to = "super::user_account::Entity",
    from = "Column::OwnerId",
    to = "super::user_account::Column::Id",
    on_update = "Cascade",
    on_delete = "Restrict"
  )]
  UserAccount3,
  #[sea_orm(
    belongs_to = "super::user_account::Entity",
    from = "Column::ReactedDirectChatReceiverId",
    to = "super::user_account::Column::Id",
    on_update = "Cascade",
    on_delete = "Restrict"
  )]
  UserAccount2,
  #[sea_orm(
    belongs_to = "super::user_account::Entity",
    from = "Column::ReactedDirectChatSenderId",
    to = "super::user_account::Column::Id",
    on_update = "Cascade",
    on_delete = "Restrict"
  )]
  UserAccount1,
}

impl Related<super::direct_chat::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::DirectChat.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
  #[sea_orm(entity = "super::direct_chat::Entity")]
  DirectChat,
  #[sea_orm(
    entity = "super::user_account::Entity",
    def = "Relation::UserAccount3.def()"
  )]
  UserAccount3,
  #[sea_orm(
    entity = "super::user_account::Entity",
    def = "Relation::UserAccount2.def()"
  )]
  UserAccount2,
  #[sea_orm(
    entity = "super::user_account::Entity",
    def = "Relation::UserAccount1.def()"
  )]
  UserAccount1,
}
