//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "friend_group_target")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub group_owner_id: Uuid,
  #[sea_orm(primary_key, auto_increment = false)]
  pub group_name: String,
  #[sea_orm(primary_key, auto_increment = false)]
  pub target_id: Uuid,
  pub created_at: DateTimeWithTimeZone,
  pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::friend_group::Entity",
    from = "(Column::GroupOwnerId, Column::GroupName)",
    to = "(super::friend_group::Column::OwnerId, super::friend_group::Column::Name)",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  FriendGroup,
  #[sea_orm(
    belongs_to = "super::user_account::Entity",
    from = "Column::GroupOwnerId",
    to = "super::user_account::Column::Id",
    on_update = "Cascade",
    on_delete = "Restrict"
  )]
  GroupOwner,
  #[sea_orm(
    belongs_to = "super::user_account::Entity",
    from = "Column::TargetId",
    to = "super::user_account::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Target,
}

impl Related<super::friend_group::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::FriendGroup.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
  #[sea_orm(entity = "super::friend_group::Entity")]
  FriendGroup,
  #[sea_orm(
    entity = "super::user_account::Entity",
    def = "Relation::GroupOwner.def()"
  )]
  GroupOwner,
  #[sea_orm(entity = "super::user_account::Entity", def = "Relation::Target.def()")]
  Target,
}
