//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "friend")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub invitor_id: Uuid,
  #[sea_orm(primary_key, auto_increment = false)]
  pub invitee_id: Uuid,
  pub created_at: DateTimeWithTimeZone,
  pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::user_account::Entity",
    from = "Column::InviteeId",
    to = "super::user_account::Column::Id",
    on_update = "Cascade",
    on_delete = "Restrict"
  )]
  Invitee,
  #[sea_orm(
    belongs_to = "super::user_account::Entity",
    from = "Column::InvitorId",
    to = "super::user_account::Column::Id",
    on_update = "Cascade",
    on_delete = "Restrict"
  )]
  Invitor,
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
  #[sea_orm(
    entity = "super::user_account::Entity",
    def = "Relation::Invitee.def()"
  )]
  Invitee,
  #[sea_orm(
    entity = "super::user_account::Entity",
    def = "Relation::Invitor.def()"
  )]
  Invitor,
}
