//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "m_states")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: i16,
  pub name: String,
  pub country_id: i16,
  pub country_code: String,
  pub fips_code: Option<String>,
  pub iso2: Option<String>,
  pub r#type: Option<String>,
  #[sea_orm(column_type = "Decimal(Some((10, 8)))", nullable)]
  pub latitude: Option<Decimal>,
  #[sea_orm(column_type = "Decimal(Some((11, 8)))", nullable)]
  pub longitude: Option<Decimal>,
  pub created_at: Option<DateTime>,
  pub updated_at: Option<DateTime>,
  pub flag: i16,
  pub wikidataid: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::m_cities::Entity")]
  MCities,
  #[sea_orm(
    belongs_to = "super::m_countries::Entity",
    from = "Column::CountryId",
    to = "super::m_countries::Column::Id",
    on_update = "Restrict",
    on_delete = "Restrict"
  )]
  MCountries,
}

impl Related<super::m_cities::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::MCities.def()
  }
}

impl Related<super::m_countries::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::MCountries.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
  #[sea_orm(entity = "super::m_cities::Entity")]
  MCities,
  #[sea_orm(entity = "super::m_countries::Entity")]
  MCountries,
}
