//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "message")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub owner_id: Uuid,
  #[sea_orm(primary_key, auto_increment = false)]
  pub receiver_id: Uuid,
  #[sea_orm(primary_key, auto_increment = false)]
  pub created_at: DateTimeWithTimeZone,
  pub message: String,
  pub updated_at: Option<DateTimeWithTimeZone>,
  pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::person::Entity",
    from = "Column::OwnerId",
    to = "super::person::Column::Id",
    on_update = "Cascade",
    on_delete = "Restrict"
  )]
  Owner,
  #[sea_orm(
    belongs_to = "super::person::Entity",
    from = "Column::ReceiverId",
    to = "super::person::Column::Id",
    on_update = "Cascade",
    on_delete = "Restrict"
  )]
  Receiver,
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
  #[sea_orm(entity = "super::person::Entity", def = "Relation::Owner.def()")]
  Owner,
  #[sea_orm(entity = "super::person::Entity", def = "Relation::Receiver.def()")]
  Receiver,
}
